liferpPrint("fine","LANGUANE Loading")
if SERVER then
	lrplanguane = CreateConVar("lrp-languane", "en", true)
end
if CLIENT then
	lrplanguane = CreateClientConVar("lrp-languane", "en", true)
end

lrplanguanes = {
	["ru"] = {
		["lrp.hint.use"] = "Нажми E",
		["lrp.territories.club"] = "Клуб",
		["lrp.cameramode"] = "Режим камеры",
		["lrp.cameramode.firstperson1"] = "Вид от первого лица",
		["lrp.cameramode.firstperson2"] = "Вид от первого лица(реалистичный)",
		["lrp.cameramode.thirdperson"] = "Вид от третьего лица",
		["lrp.russian"] = "Русский",
		["lrp.english"] = "Английский",
		["lrp.languane"] = "Язык",
		["lrp.chat"] = "Чат",
		["lrp.chat.me"] = "Действие / Мысли",
		["lrp.chat.do"] = "Действие от 3-лица",
		["lrp.chat.roll"] = "Кинуть кубик",
		["lrp.chat.try"] = "Действие с шансом",
		["lrp.chat.shout"] = "Крикнуть",
		["lrp.chat.rolling"] = "кинул кубик, выпало",
		["lrp.chat.text"] = "Введите текст",
		["lrp.chat.true"] = "Удача",
		["lrp.chat.false"] = "Неудача",
		["lrp.send"] = "Отправить",
		["lrp.accept"] = "Принять",
		["lrp.cancel"] = "Отмена",
		["lrp.shouting"] = "кричит:",
		["lrp.gestures"] = "Жесты & Танцы",
		["lrp.gestures.dance"] = "Обычный Танец",
		["lrp.gestures.striptease"] = "Стриптиз",
		["lrp.gestures.robot"] = "Робот",
		["lrp.gestures.greet"] = "Приветствие",
		["lrp.gestures.salute"] = "Салют",
		["lrp.gestures.bow"] = "Поклон",
		["lrp.gestures.laugh"] = "Насмехаться",
		["lrp.gestures.agree"] = "Одобрение",
		["lrp.gestures.becon"] = "Сюда-Сюда",
		["lrp.gestures.cheer"] = "Радоваться",
		["lrp.gestures.forward"] = "Вперед!",
		["lrp.gestures.group"] = "Группа",
		["lrp.gestures.halt"] = "Стой!",
		["lrp.gestures.pers"] = "Человек",
		["lrp.gestures.zombie"] = "Зомби",
		["lrp.cursor"] = "Курсор",
		["lrp.quests.box.name"] = "Квест Коробки",
		["lrp.quests.box.description"] = "Помогите человеку переместить коробки из точки А в точку Б",
		["lrp.quests.box.use"] = "Взять коробку",
		["lrp.npc.radius"] = "Вы должны быть рядом с NPC",
		["lrp.npc.aim"] = "Вы должны смотреть на NPC",
		["lrp.quests.box.place"] = "Положить коробку",
		["lrp.quests.box.take"] = "Вы взяли коробку. Постарайтесь её не уронить!",
		["lrp.quests.get"] = "Сначала возьми квест!",
		["lrp.quests.box.fail"] = "Ты уронил коробку! В следующий раз будь осторожен, иди и возьми новую!",
		["lrp.quests.box.successbox"] = "Молодец!",
		["lrp.quests.box.success1"] = "Спасибо! Вот твои",
		["lrp.quests.box.success2"] = "за помощь.",
		["lrp.quests.box.wherebox"] = "Возьми коробку!",
		["lrp.quests.box.taked"] = "Вы уже взяли коробку! Просто донесите её до точки Б.",
	},
	["en"] = {
		["lrp.hint.use"] = "Press E",
		["lrp.territories.club"] = "Club",
		["lrp.cameramode"] = "Camera Mode",
		["lrp.cameramode.firstperson1"] = "First-person view",
		["lrp.cameramode.firstperson2"] = "First-person view(realistic)",
		["lrp.cameramode.thirdperson"] = "Third-person view",
		["lrp.russian"] = "Russian",
		["lrp.english"] = "English",
		["lrp.languane"] = "Languane",
		["lrp.chat"] = "Chat",
		["lrp.chat.me"] = "Action / Thoughts",
		["lrp.chat.do"] = "3rd person action",
		["lrp.chat.roll"] = "Roll a die",
		["lrp.chat.try"] = "Chance action",
		["lrp.chat.shout"] = "Shout",
		["lrp.chat.rolling"] = "rolled the die, rolled",
		["lrp.chat.text"] = "Enter text",
		["lrp.chat.true"] = "Lucky",
		["lrp.chat.false"] = "Unlucky",
		["lrp.send"] = "Send",
		["lrp.accept"] = "Accept",
		["lrp.cancel"] = "Cancel",
		["lrp.shouting"] = "shout:",
		["lrp.gestures"] = "Gestures & Dancing",
		["lrp.gestures.dance"] = "Default Dance",
		["lrp.gestures.striptease"] = "Striptease",
		["lrp.gestures.robot"] = "Robot",
		["lrp.gestures.greet"] = "Greet",
		["lrp.gestures.salute"] = "Salute",
		["lrp.gestures.bow"] = "Bow",
		["lrp.gestures.laugh"] = "Laugh",
		["lrp.gestures.agree"] = "Agree",
		["lrp.gestures.becon"] = "Becon",
		["lrp.gestures.cheer"] = "Cheer",
		["lrp.gestures.forward"] = "Forward",
		["lrp.gestures.group"] = "Group",
		["lrp.gestures.halt"] = "Halt",
		["lrp.gestures.pers"] = "Pers",
		["lrp.gestures.zombie"] = "Zombie",
		["lrp.cursor"] = "Cursor",
		["lrp.quests.box.name"] = "Box's Quest",
		["lrp.quests.box.description"] = "Help the person move the boxes from point A to point B",
		["lrp.quests.box.use"] = "Take the box",
		["lrp.npc.radius"] = "You must be close to the NPC",
		["lrp.npc.aim"] = "You must look at the NPC",
		["lrp.quests.box.place"] = "Place the box",
		["lrp.quests.box.take"] = "You have taken the box. Try not to drop it!",
		["lrp.quests.get"] = "Take the quest!",
		["lrp.quests.box.fail"] = "You dropped the box! Be careful next time, go get a new one!",
		["lrp.quests.box.successbox"] = "Well done!",
		["lrp.quests.box.success1"] = "Thank you! Here's your",
		["lrp.quests.box.success2"] = "for your help.",
		["lrp.quests.box.wherebox"] = "Take the box!",
		["lrp.quests.box.taked"] = "You have already taken the box! Just get her to point B.",
	}
}

function lrpGetPhrase(phraseid)
	return lrplanguanes[lrplanguane:GetString()][phraseid]
end

liferpPrint("success","LANGUANE Loaded")